import Header from '@/components/Header';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { ReactNode } from 'react';
import '../globals.css';

type Props = Readonly<{
  children: ReactNode;
  params: { locale: string };
}>;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Function to get the translations
// async function getMessages(locale: string) {
//   try {
//     return (await import(`../../../messages/${locale}.json`)).default;
//   } catch {
//     notFound();
//   }
// }
async function getMessages(locale: string) {
  try {
    return (await import(`../../../messages/${locale}.json`)).default;
  } catch {
    return {}; // Ensure it never returns undefined
  }
}

// Function to generate the routes for all the locales
export async function generateStaticParams() {
  return ['en', 'nl'].map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }: Props) {
  const { locale } = params;
  const messages = await getMessages(locale);

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          <div className="p-5">{children}</div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
